name: Cargo Build & Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch: 

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
      
  env: 
    CARGO_TERM_COLOR: always
    
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose
      - run: cargo test --verbose
